---
# tasks file for dhcp-dns-pxe
- name: Install needed packages
  yum:
    name:
      - bind
      - bind-utils
      - vim
      - libselinux-python
    state: present

- name: Install packages for DHCP/PXE install
  yum:
    name:
      - dhcp
      - syslinux
      - tftp-server
    state: present
  when: not staticips

- name: Write out dhcp file
  template:
    src: ../templates/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  when: not staticips

- name: Write out named file
  template:
    src: ../templates/named.conf.j2
    dest: /etc/named.conf

- name: Set zone serial number
  command: "date +%Y%m%d00"
  register: dymanicserialnumber

- name: Setting serial number as a fact
  set_fact:
    serialnumber: "{{ dymanicserialnumber.stdout }}"

- name: Write out "{{ dns.domain }}" zone file
  template:
    src: ../templates/zonefile.j2
    dest: /var/named/zonefile.db

- name: Write out reverse zone file
  template:
    src: ../templates/reverse.j2
    dest: /var/named/reverse.db

- name: Open up firewall ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items:
    - 67/udp
    - 53/tcp
    - 53/udp
    - 443/tcp
    - 80/tcp
    - 8080/tcp
    - 6443/tcp
    - 6443/udp
    - 22623/tcp
    - 22623/udp
    - 9000/tcp
    - 69/udp

- name: Best effort SELinux repair - DNS
  shell: "restorecon -vR /var/named || true"

- name: Create TFTP config
  file:
    path: /var/lib/tftpboot/pxelinux.cfg
    state: directory
    mode: 0755
  when: not staticips

- name: Create TFTP RHCOS dir
  file:
    path: /var/lib/tftpboot/rhcos
    state: directory
    mode: 0755
  when: not staticips

- name: Copy over files needed for TFTP
  shell: "cp -a /usr/share/syslinux/* /var/lib/tftpboot"
  when: not staticips

  # - name: Get OCP4 installer initramfs
  #   get_url:
  #     url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/4.1.0/rhcos-4.1.0-x86_64-installer-initramfs.img
  #     dest: /var/lib/tftpboot/rhcos/initramfs.img
  #     mode: 0555
  #   when: not staticips

- name: Copy OCP4 installer initramfs
  copy:
    src: "{{ocp4fileslocation}}/rhcos-4.1.0-x86_64-installer-initramfs.img"
    dest: /var/lib/tftpboot/rhcos/initramfs.img
    mode: 0555
  when: not staticips

# - name: Get OCP4 installer kernel
#   get_url:
#     url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/4.1.0/rhcos-4.1.0-x86_64-installer-kernel
#     dest: /var/lib/tftpboot/rhcos/kernel
#     mode: 0555
#   when: not staticips

- name: Copy OCP4 installer kernel
  copy:
    url: "{{ocp4fileslocation}}/rhcos-4.1.0-x86_64-installer-kernel"
    dest: /var/lib/tftpboot/rhcos/kernel
    mode: 0555
  when: not staticips

- name: Set the default tftp file
  template:
    src: ../templates/default.j2
    dest: /var/lib/tftpboot/pxelinux.cfg/default
    mode: 0555
  when: not staticips

- name: Installing TFTP Systemd helper
  copy:
    src: ../files/start-tftp.sh
    dest: /usr/local/bin/start-tftp.sh
    mode: '0555'
  when: not staticips

- name: Installing TFTP Systemd unit file
  copy:
    src: ../files/helper-tftp.service
    dest: /etc/systemd/system/helper-tftp.service
    mode: '0655'
  when: not staticips

- name: Systemd daemon reload
  systemd:
    daemon_reload: yes
  when: not staticips

- name: Starting services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - named

- name: Starting DHCP/PXE services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - dhcpd
    - tftp
    - helper-tftp
  when: not staticips

- name: Unmasking Services
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - tftp
  when: not staticips

- name: Set the local resolv.conf file
  template:
    src: ../templates/resolv.conf.j2
    dest: /etc/resolv.conf

- name: Copy info script over
  template:
    src: ../templates/checker.sh.j2
    dest: /usr/local/bin/helpernodecheck
    owner: root
    group: root
    mode: 0555

- name: Get network interface name
  shell: "nmcli con show | tail -1 | awk '{print $1}'"
  register: networkinterfacename

- name: Setting network interface name as a fact
  set_fact:
    networkifacename: "{{ networkinterfacename.stdout }}"

- name: Setting DNS on network interface "{{ networkifacename }}" to 127.0.0.1
  command: "nmcli con mod {{ networkifacename }}  ipv4.dns 127.0.0.1"

- name: Restarting NetworkManager
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - NetworkManager

- name:  Information about this install
  debug:
    msg:
      - "Please run /usr/local/bin/helpernodecheck for information"
