---
- name: Install needed packages
  yum:
    name:
      - haproxy
    state: present
  
- name: Write out haproxy config file
  template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Open up firewall ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items:
    - 67/udp
    - 53/tcp
    - 53/udp
    - 443/tcp
    - 80/tcp
    - 8080/tcp
    - 6443/tcp
    - 6443/udp
    - 22623/tcp
    - 22623/udp
    - 9000/tcp
    - 69/udp

- name: Systemd daemon reload
  systemd:
    daemon_reload: yes
  when: not staticips

- name: Starting services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - haproxy

- name: Set the local resolv.conf file
  template:
    src: ../templates/resolv.conf.j2
    dest: /etc/resolv.conf

- name: Get network interface name
  shell: "nmcli con show | tail -1 | awk '{print $1}'"
  register: networkinterfacename

- name: Setting network interface name as a fact
  set_fact:
    networkifacename: "{{ networkinterfacename.stdout }}"

- name: Setting DNS on network interface "{{ networkifacename }}" to "{{ dns_ipv4_address }}"
  command: "nmcli con mod {{ networkifacename }}  ipv4.dns {{ dns_ipv4_address }}"

- name: Restarting NetworkManager
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - NetworkManager